version: '3.1'

services:

    springdb:
        image: mongo:4.4.11
        restart: always
        volumes:
          - mongodbvol:/data/db

    clmsearch:
        build: .
        restart: always
        ports:
            - "8680:8680"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_DATA_MONGODB_HOST=springdb
        depends_on:
            - springdb

volumes:
    mongodbvol:

