package si.um.feri.nanoclm.backend.events.vao;

public enum EventType {
    TENANT_CREATED,TENANT_ALLOWANCE_GRANTED,TENANT_ALLOWANCE_REVOKED,
    CONTACT_CREATED,CONTACT_DELETED,
    PROPERTY_SET,ATTRIBUTE_SET,COMMENT_SET
}
